name: nixpkgs-unstable-without-rustdesk-sync-24h

on:
  schedule:
    - cron: '0 4 * * *' # 4 AM UTC to avoid high-traffic peaks
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Blobless Filter
        uses: actions/checkout@v4
        with:
          ref: 'nixpkgs-unstable-without-rustdesk'
          filter: blob:none
          fetch-depth: 0 
          persist-credentials: true
          token: ${{ secrets.EDIT_WORKFLOW_FILES }}

      - name: Sync with Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote add upstream https://github.com/NixOS/nixpkgs.git
          
          git fetch upstream nixpkgs-unstable --quiet

          git rebase --quiet -X theirs upstream/nixpkgs-unstable

          git push origin nixpkgs-unstable-without-rustdesk --force-with-lease
